// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from '/Users/shishida/Desktop/shida-UI-Demo/node_modules/dumi/dist/client/theme-api/index.js';
